version: "3.8"

volumes:
  n8n_data:

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    restart: no
    volumes:
      - n8n_data:/home/node/.n8n
    ports:
      - 5678:5678
